spring:
  datasource:
    url: jdbc:mysql://114.215.209.136:3306/schoolfood?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: schoolFood
    password: YangoFood

server:
  port: 5050

# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.alexlin.yangocanteen.bean